services:
  controller:
    build:
      context: controller
    restart: unless-stopped
    privileged: true
    volumes:
      - ./controller/src:/app
    depends_on:
      - mosquitto
    env_file:
      - .env

  data-receiver:
    build:
      context: data-receiver
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data-receiver/src:/app
    depends_on:
      - mosquitto
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    user: $UID:$GID
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
