#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 60 -w 5000 -c "nc -z localhost 5000" \
    cd /app/data-receiver s6-setuidgid abc python3 -m flask --app server run --host 0.0.0.0 --port 5000 --debug
