
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Biotope Serre
  latitude: 51.05253360094072
  longitude: 3.743613677712802
  elevation: 11
  unit_system: metric
  country: BE
  time_zone: Europe/Brussels


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
